trigger:
  branches:
    include:
      - main  # or your default GitHub branch

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo "Cloning GitHub repo..."
    git clone https://github.com/muthukutty90-tech/langflow.git
    cd langflow
    
    echo "Configuring Git credentials..."
    git config user.email "marimuthu.m@sutherlandglobal.com"
    git config user.name "muthukutty90-tech"
    
    echo "Adding Azure DevOps remote..."
    git remote add azure https://6gFREwR81RGFj9Pr44cVhHdqaKSsQyLrLbNQ0xD8a45EdagRJqcfJQQJ99BDACAAAAATb2pZAAASAZDO4azY@dev.azure.com/SutherlandGlobal/Infra_Devops/_git/Test
    
    echo "Pushing code to Azure DevOps..."
    git push azure main --force
  displayName: 'Clone GitHub and Push to Azure DevOps'