trigger:
  branches:
    include:
      - main  # or the branch you want to sync from GitHub

pool:
  vmImage: 'ubuntu-latest'

steps:

- checkout: self
  clean: true

- script: |
    git config --global user.email "marimuthu.m@sutherlandglobal.com"
    git config --global user.name "muthukutty90-tech"
    git remote add azure https://github.com/muthukutty90-tech/langflow
    git push azure HEAD:main --force
  displayName: 'Sync GitHub to Azure DevOps'
